### PR TITLE
#113. Automating release build

### PR DESCRIPTION
**Pull request by sadovnikov**
See description in https://github.com/ContainerSolutions/minimesos/issues/113#issuecomment-200425774

### CODE REVIEW

**Comment by sadovnikov** [comment]
Execution line
```
./gradlew release -PgithubAuthToken=<GITHUB AUTHENTICATION TOKEN>
```

**Comment by frankscholten** [comment]
Add some documentation in README on read the docs on how to release

**Comment by sadovnikov** [comment]
@frankscholten I believe releasing is an internal process. Therefore it does not belong to README or `read the docs`. I put it on https://github.com/ContainerSolutions/minimesos/wiki/ReleaseBuild

**Comment by frankscholten** [comment]
LGTM

**Comment by alex-glv** [comment]
Ship it!

**Comment by sadovnikov** [comment]
@pullapprove wake up!!!  @alex-glv approved it! A few times ;-))

**Comment by alex-glv** [comment]
LGTM

**Pull request merged**
