### PR TITLE
#433. There is no need to enforce --mapPortsToHost parameter on MAC

### PR DESCRIPTION
**Pull request by sadovnikov**
Mapping of ports is needed when docker-machine is used and docker host is not added to the routing table. This is not MAC specific

### CODE REVIEW

**Comment by frankscholten** [comment]
Thanks @sadovnikov. Should we add code to detect Docker Machine usage and enable `--mapPortsToHost`?

**Comment by frankscholten** [comment]
Never mind. Let's not enforce this because people can choose to use routes or enable `--mapPortsToHost'.

**Comment by frankscholten** [comment]
LGTM

**Comment by sadovnikov** [comment]
Can we simply leave enabling mapPortsToHost up to the user?
On Tue, 5 Jul 2016 at 13:38, Frank Scholten <notifications@github.com>
wrote:

> Merged #463 <https://github.com/ContainerSolutions/minimesos/pull/463>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ContainerSolutions/minimesos/pull/463#event-712881860>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEh4FCGdZMkZa7Lc6Mt8t072fajkivk4ks5qSkI4gaJpZM4IxZlY>
> .
>
-- 
Viktor Sadovnikov
Software Development Process Engineer @ JV-ration

**Comment by frankscholten** [comment]
@sadovnikov Yes that's what we are doing now.

**Pull request merged**
