### PR TITLE
Set unique hostname constraints for Weave Scope

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by frankscholten** [comment]
LGTM

Thanks @errordeveloper!

**Comment by remmelt** [comment]
What does this fix?

**Comment by errordeveloper** [comment]
@remmelt it's to ensure that when user scales Scope there will be only one instance of Scope per host. There is more that needs to be done around probe discovery in multi-node setup, but this is a starting point.

**Comment by sadovnikov** [comment]
Approved

This change will have effect only after updating https://github.com/ContainerSolutions/minimesos/blob/master/minimesos/src/main/java/com/containersol/minimesos/main/CommandInit.java. Therefore #375 is created

**Comment by remmelt** [comment]
Awesome, thanks!

Groeten,

Remmelt



---

**Pull request merged**
