### PR TITLE
minimesos image is now built from a parent image

### PR DESCRIPTION
**Pull request by remmelt**
See https://github.com/ContainerSolutions/minimesos-docker

This is related to https://github.com/ContainerSolutions/minimesos/issues/318 but that still needs a decent jenkins/travis setup to build and push these images automatically.

### CODE REVIEW

**Comment by sadovnikov** [comment]
@remmelt I have two concerns about this PR
* https://hub.docker.com/r/containersol/alpine3.3-java8-jre/ does not have Dockerfile, therefore its content (and source) is unclear;
* the container, which is built here needs to container minimesos JAR. How do you get it there if the image is taken from Docker Hub and JAR is built a few seconds ago?

**Comment by alex-glv** [comment]
As @sadovnikov mentioned, can we link github repo to hub.docker.com, so we can see the Dockerfile?

**Comment by remmelt** [comment]
1) I can't create an automated build for this because Docker hub does not allow linking multiple github accounts. Who has access to the "ContainerSolutions" Docker Hub account?

2) By using the magic of `ONBUILD`.

**Comment by frankscholten** [comment]
Docker hub now has a line `Built from: https://github.com/ContainerSolutions/minimesos-docker/tree/master/alpine3.3-java8-jre`

LGTM

**Comment by sadovnikov** [comment]
@remmelt 
> By using the magic of `ONBUILD`
possibly I'm expected to understand this, but I don't. Could you explain? It's not necessary to type here ;)

**Comment by sadovnikov** [comment]
Ok, I understood this PR, but very disagree with it. It makes local development difficult, and automated release nearly impossible. Let’s chat

**Comment by remmelt** [comment]
I rebased this branch and forced an update.

**Comment by sadovnikov** [comment]
#334 is added to make `alpine3.3-java8-jre` image independent from `minimesos`

**Comment by remmelt** [comment]
Resolved https://github.com/ContainerSolutions/minimesos/issues/334 as well, because of some build context issue.

**Comment by sadovnikov** [comment]
looks good

**Comment by sadovnikov** [comment]
Approved

**Pull request merged**
