### PR TITLE
Rewrote Dockerfile to gain some speed and lose some size

### PR DESCRIPTION
**Pull request by mdirkse**
Here's my suggestion for the Dockerfile

### CODE REVIEW

**Comment by mdirkse** [comment]
Previous docker file built in +/- 2.30 minutes (on my machine) and yielded an image approximately 650 mb in size).
My docker file builds in +/- 1.30 minutes and the resulting image is about 220 mb.

I replaced the ubuntu base with Alpine (essentially following this: https://developer.atlassian.com/blog/2015/08/minimal-java-docker-containers/) and added the docker static binary, doing checksum verification of everything for security purposes.

**Comment by sadovnikov** [comment]
@frankscholten, I am a bit too new on this project to take a decision on this PR. Could you review it?

The PR result is great. However:
* were there any particular reasons to base `minimesos` containers on Ubuntu?
* if we merge this PR, it's logical to change Dockerfiles in https://github.com/ContainerSolutions/minimesos-docker too
* I remember you expressing concern about licensing of Open JDK binaries. Is it ok to pull archives with JDK from Oracle?

**Comment by sadovnikov** [comment]
@mdirkse Thank you for the PR

**Comment by sadovnikov** [comment]
just to keep this reference https://github.com/docker-library/official-images/issues/625#issuecomment-87734364

**Comment by sadovnikov** [comment]
Installation of docker by downloading the binary is implemented in the branch. Basing image on `alpine` will be implemented within #178

**Comment by frankscholten** [comment]
@sadovnikov @mdirkse This PR is closed but it does not seem to be merged. What is the status?

**Comment by jackass0528** [comment]
Hi Sir! :) I till you something about me...

#Study tools
> I working only in my smartphone
> I'm using DATA connection
> I finishing my content for now on
> I think it's easy to used the web starter kit

#situation and proposes
my purpose of this project to my parents and myself , but for now on I'm
fucosing my content in my blog site before I back to work. I spend 1year of
this code code all about and it's not easy to move on when you have empty
pocket. ;(

Anyway if you love to help me or guide me for free I willing to extension
for mount on this project. :)

Q:
*It's OK if I back out?

* it's possible that I finished this in my Android phone?

* What do you mean @sadovnikov @mdirkse ? Or i have something to delete
files that own you ?

Thanks for your concern sir! ;)

On Jan 11, 2016 11:01 PM, "Frank Scholten" <notifications@github.com> wrote:
>
> @sadovnikov @mdirkse This PR is closed but it does not seem to be merged.
What is the status?

**Comment by jackass0528** [comment]
Hi ContainerSolutions/m,

I'd like to add you to my professional network on LinkedIn.

- ronald

Confirm that you know ronald: https://www.linkedin.com/e/v2?e=0-ije3fs8r-g9&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=d_GDXna-&invitationId=6093342663514345472








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ije3fs8r-g9&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGK62qcaQiDvwAAAVI_m9v2r3561e6dBFcWLaTGC6x89FZwi4tgt4tRJnGl9A5okxzs14ucc-DsfIYJb9gLuOLF0jvlzlFvu0L_KpoIooI-2z64pdafM2RdM45YTTirTcyruHPw-C3fi1l6pnSzg1hHTQM4glv2SRi_yRzHduEg8blaHUmi9nZUOV-woj2y56-7&eid=0-ije3fs8r-g9


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ije3fs8r-g9&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jackass0528** [comment]
ronald comaling would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-ehildu-ijnkusko-tm&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=d_GDXna-&invitationID=6093342663514345472

View ronald comaling&#39;s profile: https://www.linkedin.com/e/v2?e=-ehildu-ijnkusko-tm&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=d_GDXna-&invitationID=6093342663514345472





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-ehildu-ijnkusko-tm&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-ehildu-ijnkusko-tm&loid=AQHwG9NQt4kECgAAAVJixMvS8oYib7ymbcqL_JwbuZGjZqg53vDTZ5iQNViOGrfxSfDOGH4_yRgX9oKqcq8ySGHZuQwx_wo4-5fgZRWzLc7L4FKf2fjgFBwwX4CljOpvvbbr5pPpEauHnzRXHVx5a3dZLngvPaqt2Z2o0jEB_XnytM3mzch7Q29UoQ4SQ_ejU4Cs

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-ehildu-ijnkusko-tm&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jackass0528** [comment]
ronald comaling would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-ehildu-ijxkwlpn-nd&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=d_GDXna-&invitationID=6093342663514345472

View ronald comaling&#39;s profile: https://www.linkedin.com/e/v2?e=-ehildu-ijxkwlpn-nd&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=d_GDXna-&invitationID=6093342663514345472





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-ehildu-ijxkwlpn-nd&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-ehildu-ijxkwlpn-nd&loid=AQHxh3c_idCXiwAAAVKG0YOuJxUFNIM6YgopxKiXhSusIHazBOwmp2D_FqVL3QeDEKb-hmAMF46GOeScfKnBQ6UzTSkcnHh3QXh1W7fgq-i2vISlSNRV7T7QflFbiFB--CCDszxYv8n8noENjIx31EapQXVXg5XsZfif-aThAg54YuTXhzAnXzicZIB5ZW_CTycf

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-ehildu-ijxkwlpn-nd&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sadovnikov** [comment]
@frankscholten as the comment above states: only small part of suggested changes is accepted, others will be implemented within #178

**Pull request closed without merging**
