### PR TITLE
WIP #295 minimesos now uses correct cgroup mount

### PR DESCRIPTION
**Pull request by frankscholten**

### CODE REVIEW

**Comment by frankscholten** [comment]
Fixed by changing AMI. See #295

**Comment by ddossot** [comment]
Too bad this has been abandoned because the same problem occurs when trying to run minimesos on Oracle Linux, which mounts under `/cgroup`

**Comment by frankscholten** [comment]
@ddossot Good to know! Reopening.

Could you check if the above commit fixes your problem? Feel free to add a PR for any fixes. If not we will have a look.

**Comment by ddossot** [comment]
@frankscholten Sorry I can't, I switched to plain compose instead. Note that `cat /proc/mounts | grep ^cgroup | awk '{ print $2 }' | xargs -r dirname | uniq` wasn't working on Oracle Linux, I think because `dirname` arguments are different.

**Comment by frankscholten** [comment]
@ddossot Can you paste your cgroup mounts? Perhaps we can modify the shell script so it is less platform specific.

**Comment by ddossot** [comment]
@frankscholten Here you go:
```
$ cat /proc/mounts | grep ^cgroup | awk '{ print $2 }'
/cgroup/cpuset
/cgroup/cpu
/cgroup/cpuacct
/cgroup/memory
/cgroup/devices
/cgroup/freezer
/cgroup/net_cls
/cgroup/blkio
```

**Pull request closed without merging**
