### PR TITLE
Optional components in minimesosFile

### PR DESCRIPTION
**Pull request by remmelt**
When the user would remove components after initialising a minimesosFile, and would then run `up`, mm would still start Consul, Marathon, and Registrator. This has been reduced to the three basic components: Server, 1 Agent, and ZooKeeper.

Fixes https://github.com/ContainerSolutions/minimesos/issues/346

### CODE REVIEW

**Comment by frankscholten** [comment]
@remmelt Marathon is optional however the `minimesos install` command probably breaks when Marathon is not part of the cluster. Can you check?

**Comment by sadovnikov** [comment]
LGTM

although it's in conflict with master now

**Comment by remmelt** [comment]
I rebased.

**Comment by frankscholten** [comment]
LGTM

**Comment by remmelt** [comment]
@frankscholten it shows 
```
Marathon container is not found in cluster 1988294720
```
which I think is sufficiently neat.

**Pull request merged**
