### PR TITLE
Extended cli with INFO command

### PR DESCRIPTION
**Pull request by jrslv**
```
๏ minimesos (master) > minimesos info
Minimesos cluster is not running
๏ minimesos (master) > minimesos up
http://172.17.0.186:5050
๏ minimesos (master) > minimesos info
Minimesos cluster is running
http://172.17.0.186:5050
Mesos version: 0.25.0
```

### CODE REVIEW

**Comment by jhftrifork** [comment]
Taking a look

**Comment by jhftrifork** [comment]
After making the various fixes to the `minimesos` script yesterday, the main problem I found with the `info` command was that it doesn't actually check whether the cluster is running; it just checks whether the `.minimesos/minimesos.cluster` file exists. If you run `minimesos up`, then kill all Docker containers, then run `minimesos info`, it still reports that the cluster is running.

I have no problem with merging it and opening a ticket for this.

**Comment by frankscholten** [comment]
@jhftrifork Yes please open a ticket. I will look into the PR related to this issue and others.

**Comment by jrslv** [comment]
Good point @jhftrifork.

**Comment by jhftrifork** [comment]
Opened https://github.com/ContainerSolutions/minimesos/issues/145

**Comment by jhftrifork** [comment]
@jrslv I just pushed a small change at https://github.com/ContainerSolutions/minimesos/tree/info-cli-cmd-prints-label-for-mesos-master-url

The `printMesosMasterIp` thing I've changed to `mesosMasterUrl` and I've changed it to return an `Optional<String>`. I think you can use the behavior of this method to detect whether the cluster is actually running, i.e. if it returns `Optional.empty` then the cluster is not running; if it returns `Optional.of(url)` then it really is running with a given `url` as proof. I think this is more reliable than checking for the `minimesos.cluster` file.

**Comment by jrslv** [comment]
@jhftrifork There are major changes to the `printMesosMasterIp ` thing in #130 (not merged yet)

**Pull request merged**
