### PR TITLE
Enable setting of Marathon and ZooKeeper image tags from command-line

### PR DESCRIPTION
**Pull request by mdirkse**
This patch enables you to do this:
`minimesos up --marathonImageTag=v0.13.0 --zooKeeperImageTag=3.4.2`

NOTE: if you run `./gradlew test` then you'll notice 2 tests fail, but these also currently fail on `master` (ie I didn't break anything extra).

### CODE REVIEW

**Comment by mdirkse** [comment]
@sadovnikov here's part 2 of the original pull request.

**Comment by sadovnikov** [comment]
@mdirkse What is your environment? OS, Docker or Docker Machine? what versions?
If you use Docker Machine, you need to add `route`. Plz, see "Building and running on MAC with docker-machine" on http://minimesos.readthedocs.org/en/latest/

**Comment by mdirkse** [comment]
I'm on Linux (ubuntu 15.10) Docker 1.9.1, not using Machine.

The 2 `DiscoverySystemTests` fail with the following:
```
com.github.dockerjava.api.NotFoundException: No such image: containersol/mesos-hello-world-scheduler:latest

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
```

**Comment by sadovnikov** [comment]
Thanks a lot for this PR

**Comment by sadovnikov** [comment]
Btw, I will very appreciate if you have any thoughts on #185

**Comment by sadovnikov** [comment]
@mdirkse `mesos-hello-world-scheduler` and `mesos-hello-world-executor` images become available when you run `./gradlew install`. 

Alternatively you can execute
```
./gradlew test-framework-docker:executor:buildDockerImage
./gradlew test-framework-docker:scheduler:buildDockerImage
```
before `./gradlew test`

**Comment by mdirkse** [comment]
That second method worked for me. Thanks!

**Pull request merged**
