### PR TITLE
Applied IntelliJ's automatic code formatting

### PR DESCRIPTION
**Pull request by remmelt**
As long as we have the same settings in our IDE, we will no longer have merge conflicts in imports or unnecessary code changes due to spaces/tabs/etc.

https://github.com/ContainerSolutions/minimesos/wiki/IDE-Settings

### CODE REVIEW

**Comment by alex-glv** [comment]
Looks good.
We need to add coding style settings in the wiki and .editorconfig
https://www.jetbrains.com/help/idea/2016.1/configuring-code-style.html?origin=old_help#editorconfig

**Comment by remmelt** [comment]
`.editorconfig` looks nice! Too bad they don't support the "Number of imports required for '*'" setting, and seemingly never will...

**Comment by remmelt** [comment]
Added `.editorconfig`!

**Comment by sadovnikov** [comment]
Approved

**Pull request merged**
