### PR TITLE
Update minimesos.org build url

### PR DESCRIPTION
**Pull request by alex-glv**

### CODE REVIEW

**Comment by sadovnikov** [comment]
@alex-glv I corrected the update. Returned API KEY

**Comment by sadovnikov** [comment]
Approved

**Comment by remmelt** [comment]
Check with `./gradlew  -PawsMinimesosOrgApiKey={THE API KEY} updateReleaseDocs`

How can we see that the build was triggered?

**Comment by alex-glv** [comment]
@remmelt I have updated the documentation on minimesos.org build, it's pinned in slack's minimesos channel

**Comment by alex-glv** [comment]
:+1:

**Comment by frankscholten** [comment]
LGT

**Comment by frankscholten** [comment]
Approved

**Pull request merged**
